### ISSUE TITLE
Make use of OZ initializer modifier

### ISSUE THREAD

**Issue by auryn-macmillan** [gnosis/zodiac#17]
By extending `OwnableUpgradeable` we also extend open zeppelin `Initializable` contract, which provides the `initializer`  modifier that we can use in `setUp` functions instead of having additional `initialized` var in `FactoryFriendly` contract.

We should update this in Zodiac, along with all of the modules.

- [x] Zodiac
- [x] Reality module
- [x] Bridge module
- [x] Exit module
  - [x] Circulating supply
- [x] Delay modifier
- [x] Scope guard

**Comment by cbrzn** [comment]
zodiac: https://github.com/gnosis/zodiac/pull/18
reality: https://github.com/gnosis/zodiac-module-reality/pull/51
bridge: https://github.com/gnosis/zodiac-module-bridge/pull/17
delay: https://github.com/gnosis/zodiac-modifier-delay/pull/18
exit: https://github.com/gnosis/zodiac-module-exit/pull/31
scope guard: https://github.com/gnosis/zodiac-guard-scope/pull/12

**Comment by auryn-macmillan** [comment]
Thanks @cbrzn!
