### ISSUE TITLE
Use Zodiac to add Gnosis Safe support to the Aragon client

### ISSUE THREAD

**Issue by auryn-macmillan** [gnosis/zodiac#39]
**Description:**

Gnosis Safe is the go to solution for Multisigs and blockchain vault, and Aragon provides governance solutions for communities.

For this challenge, you should integrate the Gnosis Safe into Aragon Client. The idea is that an Aragon DAO can add a Gnosis Safe vault to the DAO, and this safe can be controlled by it.

The integration should make sure of the IAvatar interface defined in the [Zodiac standard](https://github.com/gnosis/zodiac/blob/master/contracts/interfaces/IAvatar.sol) on the Gnosis Safe to allow the DAO to control Gnosis Safe via the `executeModuleTransaction()` function. There is no real contract work to be done, everything should work out of the box. So this challenge will be primarily front-end, creating an Aragon app for Aragon Client.

You can use the SafeSnap plugin for [Snapshot integration as an example](https://snapshot.org/#/weenus/proposal/QmS8p6GVJjmYUc1XuC7GXQTFQ98aPCWqLWYgtf2fd28uqB), and the [DAOHaus minion app for gnosis safe as well](https://app.daohaus.club/dao/0x1/0x6754bfb36f9d3d7771a4c3eb53507be7f1c09e49/vaults/minion/0xb0f3e8609e62154df9245dc61df6faa686ed9af2).

**Prize:** One prize of $4,000 paid in USDC

**Time commitment:** 1 week

**Submission requirements:** Code repository for a working Aragon Client App that fulfills the description (App created using Aragon UI and following Aragon guideline - https://hack.aragon.org/docs/tutorial)

**Judging criteria:** Fulfills all requirements, and provides the best UI.

**Winner announcement date:** 27th of November

**Resources:**
- [Aragon Apps Tutorial](https://hack.aragon.org/docs/tutorial)
- [Zodiac repo](https://github.com/gnosis/zodiac)
- [Zodiac docs](https://gnosis.github.io/zodiac/)
- [Gnosis Safe Core SDK](https://github.com/gnosis/safe-core-sdk)
- [Ethers-multisend library](https://github.com/gnosis/ethers-multisend) (not production ready)
- [React-multisend library](https://github.com/gnosis/react-multisend) (not production ready)

**Comment by ht55ght55** [comment]
Is there any news on this?  Is it too late to try to claim this bounty?

**Comment by auryn-macmillan** [comment]
> Is there any news on this? Is it too late to try to claim this bounty?

No news on it yet. No one has submitted yet, so definitely not too late to try to claim this one.
